---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "6.3.0"

inputs:
  - name: git-repo

caches:
  - path: git-repo/node_modules

run:
  path: git-repo/ci/scripts/unit.sh
