jobs:
# - name: unit-tests
#   plan:
#   - get: git-repo
#     trigger: true
#   - task: unit
#     file: git-repo/ci/tasks/unit.yml

- name: deploy-prod
  plan:
  - get: git-repo
    # passed: [unit-tests]
    trigger: true
  - get: version
    params: {bump: minor}
  - task: install-dependencies
    file: git-repo/ci/tasks/install-dependencies.yml
    timeout: 5m
  - put: pws
    params:
      manifest: git-repo/manifest-prod.yml
      current_app_name: pcfsizer
      path: pcfsizer
  - put: git-repo
    params:
      repository: git-repo
      tag: version/number
  - put: version
    params: {file: version/number}



resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
    private_key: {{GIT_PRIVATE_KEY}}

- name: pws
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}

- name: version
  type: semver
  source:
    bucket: {{S3_BUCKET}}
    key: pcfsizer/current-version
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0
