jobs:
- name: unit-tests
  plan:
  - get: git-repo
    trigger: true
  - task: unit
    file: git-repo/ci/tasks/unit.yml

- name: deploy-test
  plan:
  - get: git-repo
    passed: [unit-tests]
    trigger: true
  - task: install-dependencies
    file: git-repo/ci/tasks/install-dependencies.yml
    timeout: 5m
  - put: pws
    params:
      manifest: git-repo/manifest.yml
      current_app_name: pcfsizer-dev
      path: pcfsizer

resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: develop
    private_key: {{GIT_PRIVATE_KEY}}

- name: pws
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
